matrix:
    include:
        - language: java
          before_script: cd NL2BashWebScraper

        - language: python
          python: "3.6"
          before_script: cd nl2bash_server
          install:
            - pip install pipenv
          script:
            # - pytest
            - export PIPENV_IGNORE_VIRTUALENVS=1
            - pipenv install
            # - pipenv install
            - pipenv run python manage.py migrate
            - pipenv run python -m nl2bash_server.add_data_from_scraper test_pages/ScrapedPages
            # - timeout --preserve-status 10 pipenv run python manage.py runserver

notifications:
    email: false
